# Generated by Django 4.2.11 on 2026-04-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryrecord',
            name='english',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dictionaryrecord',
            name='russian',
            field=models.CharField(max_length=50),
        ),
    ]
