# Generated by Django 4.2.11 on 2026-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_dictionaryrecord_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryrecord',
            name='english',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dictionaryrecord',
            name='russian',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
